version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wp123
    networks:
      dokploy-network:
        aliases:
          - db
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 10s
      retries: 15

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wp123
      WORDPRESS_DB_NAME: wordpress
    networks:
      dokploy-network:
        aliases:
          - wordpress
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`tour360.braviaglobal.com.br` )
      - traefik.http.routers.wordpress.entrypoints=web
      - traefik.http.services.wordpress.loadbalancer.server.port=80
    command: sh -c 'while ! mysqladmin ping -hdb --silent; do sleep 1; done; wordpress-entrypoint.sh apache2-foreground'
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost/wp-admin/install.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  dokploy-network:
    external: true

volumes:
  db_data:
